table cohort_retention

	measure 'Cohort Retention' = DIVIDE ( SUM ( cohort_retention[retained] ), SUM ( cohort_retention[cohort_size] ) )
		formatString: 0.0%

	column cohort_week
		dataType: dateTime
		formatString: yyyy-mm-dd
		summarizeBy: none
		sourceColumn: cohort_week

	column day_n
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: day_n

	column cohort_size
		dataType: int64
		formatString: #,0
		summarizeBy: sum
		sourceColumn: cohort_size

	column retained
		dataType: double
		formatString: #,0.00
		summarizeBy: sum
		sourceColumn: retained

	column retention
		dataType: double
		formatString: 0.0%
		summarizeBy: none
		sourceColumn: retention

	partition cohort_retention = m
		mode: import
		source =
				let
				    Source = Csv.Document(
				        if Text.StartsWith(DataFolder, "http")
				            then Web.Contents(DataFolder, [RelativePath = "cohort_retention.csv"])
				            else File.Contents(DataFolder & "cohort_retention.csv"),
				        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
				    ),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {
				        {"cohort_week", type date},
				        {"day_n", Int64.Type},
				        {"cohort_size", Int64.Type},
				        {"retained", type number},
				        {"retention", type number}
				    }, "en-US")
				in
				    Typed
