table retention_curve

	measure 'Day-N Retention' = DIVIDE ( SUM ( retention_curve[retained] ), SUM ( retention_curve[eligible] ) )
		formatString: 0.0%

	column day_n
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: day_n

	column eligible
		dataType: int64
		formatString: #,0
		summarizeBy: sum
		sourceColumn: eligible

	column retained
		dataType: int64
		formatString: #,0
		summarizeBy: sum
		sourceColumn: retained

	column retention
		dataType: double
		formatString: 0.0%
		summarizeBy: none
		sourceColumn: retention

	partition retention_curve = m
		mode: import
		source =
				let
				    Source = Csv.Document(
				        if Text.StartsWith(DataFolder, "http")
				            then Web.Contents(DataFolder, [RelativePath = "retention_curve.csv"])
				            else File.Contents(DataFolder & "retention_curve.csv"),
				        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
				    ),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {
				        {"day_n", Int64.Type},
				        {"eligible", Int64.Type},
				        {"retained", Int64.Type},
				        {"retention", type number}
				    }, "en-US")
				in
				    Typed
